baseURL: 'https://hecht.space/'
title: Matthias Hecht | hecht.space | DEVELOPER - MUSICIAN
theme: PaperMod
languageCode: en-us
enableEmoji: true
author:
  name: "Matthias Hecht"
  email: info@hecht.space

enableRobotsTXT: true
paginate: 5
minify:
  disableXML: true
  minifyOutput: true
  
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
  

params:
  assets:
    disableFingerprinting: true #See https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#failed-to-find-a-valid-digest-in-the-integrity-attribute-for-resource--
  defaultTheme: auto # theme
  ShowShareButtons: true # theme
  ShowReadingTime: true # theme
  ShowToc: true # theme
  tocopen: true # theme
  title: Matthias Hecht | hecht.space | DEVELOPER - MUSICIAN # theme
  description: 'Matthias Hecht | hecht.space | DEVELOPER - MUSICIAN' # theme
  author: Matthias Hecht # theme
  linkedin: https://www.linkedin.com/in/matthias-hecht-931851164/
  xing: https://www.xing.com/profile/Matthias_Hecht20/
  github: https://github.com/matzehecht
  npm: https://www.npmjs.com/~matzehecht
  musescore: https://musescore.com/user/1060136
  iconOrder: ['LinkedIn', 'Xing', 'GitHub', 'npm', 'MuseScore']
  displayFullLangName: true
  fuseOpts: # options for search feature of theme
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']
    
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true

defaultContentLanguage: en
languages:
  en:
    languageName: 'English'
    weight: 1

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary for search feature of theme
